### ISSUE TITLE
请问运行后登录的用户名和密码是什么？

### ISSUE THREAD

**Issue by SeptSky** [17MKH/Mkh.UI#5]
请问运行后登录的用户名和密码是什么？使用admin/123456无法登录。另外，运行后的界面默认是英文，右上角的语言切换弹出菜单为空，与演示网站的效果不一致。
谢谢！

**Comment by SeptSky** [comment]
还以为是前端的界面代码呢。

**Comment by iamoldli** [comment]
用户名是17mkh  密码 123456
这个只是前端框架代码，不是演示网站源码

**Comment by SeptSky** [comment]
收到，谢谢！
